AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation template to ctreate EC2 instance with Security group that allows HTTP traffic from 
Parameters:
 SubnetID:
  Type: String
Mappings:
  ServiceMap:
    SearchServiceCucumber:
      InstanceType: t2.micro
  RegionMap:
    eu-west-1:
      ImageId: ami-0069d66985b09d219
    
Resources:
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: SearchServiceCucumberGroup
  
  ExecutionRoleS3Access:
    Type: AWS::IAM::Role
    Properties:
      RoleName: cucumberDockerAccess
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess

  SearchServiceCucumberProfile:
    Type: AWS::IAM::InstanceProfile
    Properties: 
      InstanceProfileName: sscucumberProfile
      Path: /
      Roles: 
       - !Ref ExecutionRoleS3Access

  SearchServiceCucumberGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for search service cucumber container
      VpcId: vpc-5273c62b
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5050
          ToPort: 5050
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  SearchServiceCucumberInstance:
    Type: AWS::EC2::Instance
    Properties:
      SubnetId: subnet-219e7858
      SecurityGroupIds:
        - Ref: SearchServiceCucumberGroup
      IamInstanceProfile: !Ref SearchServiceCucumberProfile
      InstanceType:
        Fn::FindInMap:
          - ServiceMap
          - SearchServiceCucumber
          - InstanceType
      ImageId:
        Fn::FindInMap:
          - RegionMap
          - Ref: AWS::Region
          - ImageId
      Tags:
        - Key: Name
          Value: "SearchServiceCucumberInstance"

      UserData:
        Fn::Base64:
         Fn::Sub: |
            #!/bin/bash
            sudo yum update -y

            sudo amazon-linux-extras install docker
            sudo service docker start
            sudo systemctl enable docker
            sudo usermod -a -G docker ec2-user

            wget https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m) 
            sudo mv docker-compose-$(uname -s)-$(uname -m) /usr/local/bin/docker-compose
            sudo chmod -v +x /usr/local/bin/docker-compose

            chkconfig docker on
            docker info

            sudo chmod 666 /var/run/docker.sock

            aws s3 cp s3://test-upload-77/docker-compose/docker-compose.yml /home/ec2-user
            docker-compose -f /home/ec2-user/docker-compose.yml up -d
                  
Outputs:
  InstanceId:
    Description: InstanceId of the newly created EC2 instance
    Value: !Ref SearchServiceCucumberInstance
  PublicDNS:
    Description: Public DNSName of the newly created EC2 instance
    Value: !GetAtt [SearchServiceCucumberInstance, PublicDnsName]

          