AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation template to ctreate EC2 instance with Security group that allows HTTP traffic from 
Parameters:
 SubnetID:
  Type: String
Mappings:
  ServiceMap:
    SSCucumber:
      InstanceType: t2.micro
  RegionMap:
    eu-west-1:
      ImageId: ami-0c8f57f5b12c42d4a
    
Resources:
  SSGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: SSGroup
  
  ExecutionRoleS3Access:
    Type: AWS::IAM::Role
    Properties:
      RoleName: cucumberDockerAccess
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess

  SSProfile:
    Type: AWS::IAM::InstanceProfile
    Properties: 
      InstanceProfileName: SSProfile
      Path: /
      Roles: 
       - !Ref ExecutionRoleS3Access

  SSSGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for SS container
      VpcId: vpc-5273c62b
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5050
          ToPort: 5050
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  SSInstance:
    Type: AWS::EC2::Instance
    Properties:
      SubnetId: subnet-219e7858
      SecurityGroupIds:
        - Ref: SSSGroup
      IamInstanceProfile: !Ref SSProfile
      InstanceType:
        Fn::FindInMap:
          - ServiceMap
          - SSCucumber
          - InstanceType
      ImageId:
        Fn::FindInMap:
          - RegionMap
          - Ref: AWS::Region
          - ImageId
      Tags:
        - Key: Name
          Value: "SSInstanceDemo"

      UserData:
        Fn::Base64:
         Fn::Sub: |
            #!/bin/bash
            aws s3 cp s3://test-upload-77/docker-compose/docker-compose.yaml /home/ec2-user
            docker-compose -f /home/ec2-user/docker-compose.yaml up -d

            
                  
Outputs:
  InstanceId:
    Description: InstanceId of the newly created EC2 instance
    Value: !Ref SSInstance
  PublicDNS:
    Description: Public DNSName of the newly created EC2 instance
    Value: !GetAtt [SSInstance, PublicDnsName]

          