AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation template for ECS creation
Parameters:
 SubnetID:
  Type: String

    
Resources:
  ECSCluster:
   Type: 'AWS::ECS::Cluster'
   Properties:
    ClusterName: deployment-example-cluster
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: deployment-example-log-group
  ContainerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: ContainerSecurityGroup
      GroupDescription: Security group for NGINX container
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
