version: "3.9"
services:
  hello-world:
    image: vad1mo/hello-world-rest
    ports:
      - "5050:5050"
    restart: unless-stopped
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"