version: "3.2"
services:
 web:
    image: "rambo29/sample-jenkins-demo"
    ports:
      - "8000:8383"
    depends_on:
      - redis
      - db
 redis:
    image: "redis:alpine"

    command: redis-server

    ports:
     - "8081:6379"
 db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'